/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hqwx.plugin.depe;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class HqwxDependPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("depe", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'com.hqwx.plugin.depe.greeting'"));
        });
    }
}
